export const genres = [
  { name: 'Jazz' },
  { name: 'Soul' },
  { name: 'Pop' },
  { name: 'Blues' },
];

export const artists = [
  {
    name: 'Charles Aznavour',
    bio: 'Famous French-Armenian singer and songwriter.',
    profile_picture: 'aznavour.jpg',
  },
  {
    name: 'Ray Charles',
    bio: 'American singer, songwriter, and pianist.',
    profile_picture: 'ray_charles.jpg',
  },
  {
    name: 'Frank Sinatra',
    bio: 'American singer and actor, one of the most popular entertainers of the 20th century.',
    profile_picture: 'frank_sinatra.jpg',
  },
  {
    name: 'Stevie Wonder',
    bio: 'American singer, songwriter, musician, and record producer.',
    profile_picture: 'stevie_wonder.jpg',
  },
];

export const albums = [
  {
    title: 'Best of Aznavour',
    release_date: '1974-01-01',
    cover_image: 'she.jpg',
    artist: 'Charles Aznavour',
  },
  {
    title: 'Genius Loves Company',
    release_date: '2004-08-31',
    cover_image: 'genius_loves_company.jpg',
    artist: 'Ray Charles',
  },
  {
    title: 'In the Wee Small Hours',
    release_date: '1955-04-25',
    cover_image: 'in_the_wee_small_hours.jpg',
    artist: 'Frank Sinatra',
  },
  {
    title: 'Songs in the Key of Life',
    release_date: '1976-09-28',
    cover_image: 'songs_in_the_key_of_life.jpg',
    artist: 'Stevie Wonder',
  },
];

export const songs = [
  // Charles Aznavour - She
  {
    title: 'She',
    duration: 240,
    audio_file: 'she.mp3',
    artist: 'Charles Aznavour',
    album: 'She',
    genres: ['Jazz', 'Pop'],
  },
  {
    title: 'The Old Fashioned Way',
    duration: 230,
    audio_file: 'the_old_fashioned_way.mp3',
    artist: 'Charles Aznavour',
    album: 'She',
    genres: ['Pop'],
  },
  {
    title: 'La Bohème',
    duration: 220,
    audio_file: 'la_boheme.mp3',
    artist: 'Charles Aznavour',
    album: 'She',
    genres: ['Jazz'],
  },
  {
    title: 'Yesterday When I Was Young',
    duration: 210,
    audio_file: 'yesterday_when_i_was_young.mp3',
    artist: 'Charles Aznavour',
    album: 'She',
    genres: ['Pop', 'Jazz'],
  },
  {
    title: 'For Me Formidable',
    duration: 200,
    audio_file: 'for_me_formidable.mp3',
    artist: 'Charles Aznavour',
    album: 'She',
    genres: ['Pop'],
  },
  {
    title: 'Emmenez-moi',
    duration: 250,
    audio_file: 'emmenez_moi.mp3',
    artist: 'Charles Aznavour',
    album: 'She',
    genres: ['Jazz'],
  },
  {
    title: 'Comme Ils Disent',
    duration: 230,
    audio_file: 'comme_ils_disent.mp3',
    artist: 'Charles Aznavour',
    album: 'She',
    genres: ['Pop'],
  },
  {
    title: 'Parce Que Tu Crois',
    duration: 210,
    audio_file: 'parce_que_tu_crois.mp3',
    artist: 'Charles Aznavour',
    album: 'She',
    genres: ['Jazz'],
  },
  {
    title: 'Ave Maria',
    duration: 180,
    audio_file: 'ave_maria.mp3',
    artist: 'Charles Aznavour',
    album: 'She',
    genres: ['Pop', 'Jazz'],
  },
  {
    title: 'Tous Les Visages De L’Amour',
    duration: 220,
    audio_file: 'tous_les_visages.mp3',
    artist: 'Charles Aznavour',
    album: 'She',
    genres: ['Jazz', 'Pop'],
  },

  // Ray Charles - Genius Loves Company
  {
    title: 'Hit the Road Jack',
    duration: 180,
    audio_file: 'hit_the_road_jack.mp3',
    artist: 'Ray Charles',
    album: 'Genius Loves Company',
    genres: ['Jazz', 'Blues'],
  },
  {
    title: 'Georgia on My Mind',
    duration: 240,
    audio_file: 'georgia_on_my_mind.mp3',
    artist: 'Ray Charles',
    album: 'Genius Loves Company',
    genres: ['Blues', 'Jazz'],
  },
  {
    title: 'You Don’t Know Me',
    duration: 230,
    audio_file: 'you_dont_know_me.mp3',
    artist: 'Ray Charles',
    album: 'Genius Loves Company',
    genres: ['Jazz'],
  },
  {
    title: 'Unchain My Heart',
    duration: 210,
    audio_file: 'unchain_my_heart.mp3',
    artist: 'Ray Charles',
    album: 'Genius Loves Company',
    genres: ['Blues'],
  },
  {
    title: 'Let’s Go Get Stoned',
    duration: 250,
    audio_file: 'lets_go_get_stoned.mp3',
    artist: 'Ray Charles',
    album: 'Genius Loves Company',
    genres: ['Blues'],
  },
  {
    title: 'I Can’t Stop Loving You',
    duration: 220,
    audio_file: 'i_cant_stop_loving_you.mp3',
    artist: 'Ray Charles',
    album: 'Genius Loves Company',
    genres: ['Jazz'],
  },
  {
    title: 'Crying Time',
    duration: 200,
    audio_file: 'crying_time.mp3',
    artist: 'Ray Charles',
    album: 'Genius Loves Company',
    genres: ['Blues'],
  },
  {
    title: 'What’d I Say',
    duration: 250,
    audio_file: 'whatd_i_say.mp3',
    artist: 'Ray Charles',
    album: 'Genius Loves Company',
    genres: ['Blues', 'Jazz'],
  },
  {
    title: 'Busted',
    duration: 230,
    audio_file: 'busted.mp3',
    artist: 'Ray Charles',
    album: 'Genius Loves Company',
    genres: ['Jazz'],
  },
  {
    title: 'America the Beautiful',
    duration: 270,
    audio_file: 'america_the_beautiful.mp3',
    artist: 'Ray Charles',
    album: 'Genius Loves Company',
    genres: ['Blues'],
  },

  // Frank Sinatra - In the Wee Small Hours
  {
    title: 'Fly Me to the Moon',
    duration: 145,
    audio_file: 'fly_me_to_the_moon.mp3',
    artist: 'Frank Sinatra',
    album: 'In the Wee Small Hours',
    genres: ['Jazz'],
  },
  {
    title: 'I Get a Kick Out of You',
    duration: 180,
    audio_file: 'i_get_a_kick_out_of_you.mp3',
    artist: 'Frank Sinatra',
    album: 'In the Wee Small Hours',
    genres: ['Jazz'],
  },
  {
    title: 'I’ve Got You Under My Skin',
    duration: 210,
    audio_file: 'ive_got_you_under_my_skin.mp3',
    artist: 'Frank Sinatra',
    album: 'In the Wee Small Hours',
    genres: ['Jazz'],
  },
  {
    title: 'My Way',
    duration: 245,
    audio_file: 'my_way.mp3',
    artist: 'Frank Sinatra',
    album: 'In the Wee Small Hours',
    genres: ['Jazz'],
  },
  {
    title: 'Strangers in the Night',
    duration: 230,
    audio_file: 'strangers_in_the_night.mp3',
    artist: 'Frank Sinatra',
    album: 'In the Wee Small Hours',
    genres: ['Jazz'],
  },
  {
    title: 'The Lady is a Tramp',
    duration: 225,
    audio_file: 'the_lady_is_a_tramp.mp3',
    artist: 'Frank Sinatra',
    album: 'In the Wee Small Hours',
    genres: ['Jazz'],
  },
  {
    title: 'Night and Day',
    duration: 240,
    audio_file: 'night_and_day.mp3',
    artist: 'Frank Sinatra',
    album: 'In the Wee Small Hours',
    genres: ['Jazz'],
  },
  {
    title: 'Young at Heart',
    duration: 200,
    audio_file: 'young_at_heart.mp3',
    artist: 'Frank Sinatra',
    album: 'In the Wee Small Hours',
    genres: ['Jazz'],
  },
  {
    title: 'Come Fly With Me',
    duration: 210,
    audio_file: 'come_fly_with_me.mp3',
    artist: 'Frank Sinatra',
    album: 'In the Wee Small Hours',
    genres: ['Jazz'],
  },
  {
    title: 'Witchcraft',
    duration: 220,
    audio_file: 'witchcraft.mp3',
    artist: 'Frank Sinatra',
    album: 'In the Wee Small Hours',
    genres: ['Jazz'],
  },

  // Stevie Wonder - Songs in the Key of Life
  {
    title: 'Isn’t She Lovely',
    duration: 210,
    audio_file: 'isnt_she_lovely.mp3',
    artist: 'Stevie Wonder',
    album: 'Songs in the Key of Life',
    genres: ['Soul', 'Pop'],
  },
  {
    title: 'Sir Duke',
    duration: 225,
    audio_file: 'sir_duke.mp3',
    artist: 'Stevie Wonder',
    album: 'Songs in the Key of Life',
    genres: ['Soul'],
  },
  {
    title: 'I Wish',
    duration: 240,
    audio_file: 'i_wish.mp3',
    artist: 'Stevie Wonder',
    album: 'Songs in the Key of Life',
    genres: ['Soul', 'Pop'],
  },
  {
    title: 'Pastime Paradise',
    duration: 250,
    audio_file: 'pastime_paradise.mp3',
    artist: 'Stevie Wonder',
    album: 'Songs in the Key of Life',
    genres: ['Soul'],
  },
  {
    title: 'Isn’t She Lovely',
    duration: 210,
    audio_file: 'isnt_she_lovely.mp3',
    artist: 'Stevie Wonder',
    album: 'Songs in the Key of Life',
    genres: ['Soul'],
  },
  {
    title: 'Golden Lady',
    duration: 240,
    audio_file: 'golden_lady.mp3',
    artist: 'Stevie Wonder',
    album: 'Songs in the Key of Life',
    genres: ['Soul'],
  },
  {
    title: 'Joy Inside My Tears',
    duration: 245,
    audio_file: 'joy_inside_my_tears.mp3',
    artist: 'Stevie Wonder',
    album: 'Songs in the Key of Life',
    genres: ['Soul'],
  },
  {
    title: 'Knocks Me Off My Feet',
    duration: 220,
    audio_file: 'knocks_me_off_my_feet.mp3',
    artist: 'Stevie Wonder',
    album: 'Songs in the Key of Life',
    genres: ['Soul'],
  },
  {
    title: 'Living for the City',
    duration: 300,
    audio_file: 'living_for_the_city.mp3',
    artist: 'Stevie Wonder',
    album: 'Songs in the Key of Life',
    genres: ['Soul'],
  },
  {
    title: 'All Day Sucker',
    duration: 240,
    audio_file: 'all_day_sucker.mp3',
    artist: 'Stevie Wonder',
    album: 'Songs in the Key of Life',
    genres: ['Soul'],
  },
];
